// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: veranablockchain/trustregistry/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e500ee22150b7e8, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e500ee22150b7e8, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryGetTrustRegistryRequest is the request type for the Query/GetTrustRegistry RPC method.
type QueryGetTrustRegistryRequest struct {
	Did               string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	ActiveGfOnly      bool   `protobuf:"varint,2,opt,name=active_gf_only,json=activeGfOnly,proto3" json:"active_gf_only,omitempty"`
	PreferredLanguage string `protobuf:"bytes,3,opt,name=preferred_language,json=preferredLanguage,proto3" json:"preferred_language,omitempty"`
}

func (m *QueryGetTrustRegistryRequest) Reset()         { *m = QueryGetTrustRegistryRequest{} }
func (m *QueryGetTrustRegistryRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetTrustRegistryRequest) ProtoMessage()    {}
func (*QueryGetTrustRegistryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e500ee22150b7e8, []int{2}
}
func (m *QueryGetTrustRegistryRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetTrustRegistryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetTrustRegistryRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetTrustRegistryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTrustRegistryRequest.Merge(m, src)
}
func (m *QueryGetTrustRegistryRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetTrustRegistryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTrustRegistryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTrustRegistryRequest proto.InternalMessageInfo

func (m *QueryGetTrustRegistryRequest) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

func (m *QueryGetTrustRegistryRequest) GetActiveGfOnly() bool {
	if m != nil {
		return m.ActiveGfOnly
	}
	return false
}

func (m *QueryGetTrustRegistryRequest) GetPreferredLanguage() string {
	if m != nil {
		return m.PreferredLanguage
	}
	return ""
}

// QueryGetTrustRegistryResponse is the response type for the Query/GetTrustRegistry RPC method.
type QueryGetTrustRegistryResponse struct {
	TrustRegistry *TrustRegistry                `protobuf:"bytes,1,opt,name=trust_registry,json=trustRegistry,proto3" json:"trust_registry,omitempty"`
	Versions      []GovernanceFrameworkVersion  `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions"`
	Documents     []GovernanceFrameworkDocument `protobuf:"bytes,3,rep,name=documents,proto3" json:"documents"`
}

func (m *QueryGetTrustRegistryResponse) Reset()         { *m = QueryGetTrustRegistryResponse{} }
func (m *QueryGetTrustRegistryResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetTrustRegistryResponse) ProtoMessage()    {}
func (*QueryGetTrustRegistryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e500ee22150b7e8, []int{3}
}
func (m *QueryGetTrustRegistryResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetTrustRegistryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetTrustRegistryResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetTrustRegistryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTrustRegistryResponse.Merge(m, src)
}
func (m *QueryGetTrustRegistryResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetTrustRegistryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTrustRegistryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTrustRegistryResponse proto.InternalMessageInfo

func (m *QueryGetTrustRegistryResponse) GetTrustRegistry() *TrustRegistry {
	if m != nil {
		return m.TrustRegistry
	}
	return nil
}

func (m *QueryGetTrustRegistryResponse) GetVersions() []GovernanceFrameworkVersion {
	if m != nil {
		return m.Versions
	}
	return nil
}

func (m *QueryGetTrustRegistryResponse) GetDocuments() []GovernanceFrameworkDocument {
	if m != nil {
		return m.Documents
	}
	return nil
}

// QueryListTrustRegistriesRequest is the request type for the Query/ListTrustRegistries RPC method.
type QueryListTrustRegistriesRequest struct {
	Modified          *time.Time `protobuf:"bytes,1,opt,name=modified,proto3,stdtime" json:"modified,omitempty"`
	ActiveGfOnly      bool       `protobuf:"varint,2,opt,name=active_gf_only,json=activeGfOnly,proto3" json:"active_gf_only,omitempty"`
	PreferredLanguage string     `protobuf:"bytes,3,opt,name=preferred_language,json=preferredLanguage,proto3" json:"preferred_language,omitempty"`
	ResponseMaxSize   uint32     `protobuf:"varint,4,opt,name=response_max_size,json=responseMaxSize,proto3" json:"response_max_size,omitempty"`
}

func (m *QueryListTrustRegistriesRequest) Reset()         { *m = QueryListTrustRegistriesRequest{} }
func (m *QueryListTrustRegistriesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListTrustRegistriesRequest) ProtoMessage()    {}
func (*QueryListTrustRegistriesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e500ee22150b7e8, []int{4}
}
func (m *QueryListTrustRegistriesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListTrustRegistriesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListTrustRegistriesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListTrustRegistriesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListTrustRegistriesRequest.Merge(m, src)
}
func (m *QueryListTrustRegistriesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListTrustRegistriesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListTrustRegistriesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListTrustRegistriesRequest proto.InternalMessageInfo

func (m *QueryListTrustRegistriesRequest) GetModified() *time.Time {
	if m != nil {
		return m.Modified
	}
	return nil
}

func (m *QueryListTrustRegistriesRequest) GetActiveGfOnly() bool {
	if m != nil {
		return m.ActiveGfOnly
	}
	return false
}

func (m *QueryListTrustRegistriesRequest) GetPreferredLanguage() string {
	if m != nil {
		return m.PreferredLanguage
	}
	return ""
}

func (m *QueryListTrustRegistriesRequest) GetResponseMaxSize() uint32 {
	if m != nil {
		return m.ResponseMaxSize
	}
	return 0
}

// QueryListTrustRegistriesResponse is the response type for the Query/ListTrustRegistries RPC method.
type QueryListTrustRegistriesResponse struct {
	TrustRegistries []TrustRegistry `protobuf:"bytes,1,rep,name=trust_registries,json=trustRegistries,proto3" json:"trust_registries"`
}

func (m *QueryListTrustRegistriesResponse) Reset()         { *m = QueryListTrustRegistriesResponse{} }
func (m *QueryListTrustRegistriesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListTrustRegistriesResponse) ProtoMessage()    {}
func (*QueryListTrustRegistriesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3e500ee22150b7e8, []int{5}
}
func (m *QueryListTrustRegistriesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListTrustRegistriesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListTrustRegistriesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListTrustRegistriesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListTrustRegistriesResponse.Merge(m, src)
}
func (m *QueryListTrustRegistriesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListTrustRegistriesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListTrustRegistriesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListTrustRegistriesResponse proto.InternalMessageInfo

func (m *QueryListTrustRegistriesResponse) GetTrustRegistries() []TrustRegistry {
	if m != nil {
		return m.TrustRegistries
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "veranablockchain.trustregistry.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "veranablockchain.trustregistry.QueryParamsResponse")
	proto.RegisterType((*QueryGetTrustRegistryRequest)(nil), "veranablockchain.trustregistry.QueryGetTrustRegistryRequest")
	proto.RegisterType((*QueryGetTrustRegistryResponse)(nil), "veranablockchain.trustregistry.QueryGetTrustRegistryResponse")
	proto.RegisterType((*QueryListTrustRegistriesRequest)(nil), "veranablockchain.trustregistry.QueryListTrustRegistriesRequest")
	proto.RegisterType((*QueryListTrustRegistriesResponse)(nil), "veranablockchain.trustregistry.QueryListTrustRegistriesResponse")
}

func init() {
	proto.RegisterFile("veranablockchain/trustregistry/query.proto", fileDescriptor_3e500ee22150b7e8)
}

var fileDescriptor_3e500ee22150b7e8 = []byte{
	// 737 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0x4d, 0x6b, 0x53, 0x4d,
	0x14, 0xce, 0x24, 0x7d, 0x4b, 0x3a, 0x7d, 0xfb, 0x91, 0x69, 0x79, 0xdf, 0x10, 0x6a, 0x12, 0x82,
	0x48, 0x88, 0xf4, 0x0e, 0x4d, 0x71, 0x63, 0xfd, 0x28, 0x41, 0x2c, 0x42, 0x45, 0xbd, 0x16, 0x11,
	0x11, 0xe3, 0x24, 0x77, 0x72, 0x3b, 0x34, 0xf7, 0xce, 0xed, 0xcc, 0x24, 0x36, 0x15, 0x37, 0x05,
	0xf7, 0x05, 0xb7, 0xfe, 0x00, 0x37, 0x8a, 0x82, 0x3f, 0xa2, 0xcb, 0x82, 0x1b, 0x57, 0x55, 0xda,
	0x82, 0x7f, 0x43, 0x32, 0x77, 0x12, 0x9b, 0xda, 0x98, 0xb6, 0xe0, 0x26, 0xcc, 0x9d, 0x39, 0xe7,
	0x39, 0xcf, 0x73, 0xe6, 0x39, 0x13, 0x58, 0x68, 0x52, 0x41, 0x7c, 0x52, 0xa9, 0xf3, 0xea, 0x5a,
	0x75, 0x95, 0x30, 0x1f, 0x2b, 0xd1, 0x90, 0x4a, 0x50, 0x97, 0x49, 0x25, 0x5a, 0x78, 0xbd, 0x41,
	0x45, 0xcb, 0x0a, 0x04, 0x57, 0x1c, 0xa5, 0x8f, 0xc7, 0x5a, 0x3d, 0xb1, 0xa9, 0x04, 0xf1, 0x98,
	0xcf, 0xb1, 0xfe, 0x0d, 0x53, 0x52, 0xd3, 0x2e, 0x77, 0xb9, 0x5e, 0xe2, 0xf6, 0xca, 0xec, 0xce,
	0xb8, 0x9c, 0xbb, 0x75, 0x8a, 0x49, 0xc0, 0x30, 0xf1, 0x7d, 0xae, 0x88, 0x62, 0xdc, 0x97, 0xe6,
	0xb4, 0x50, 0xe5, 0xd2, 0xe3, 0x12, 0x57, 0x88, 0xa4, 0x61, 0x7d, 0xdc, 0x9c, 0xab, 0x50, 0x45,
	0xe6, 0x70, 0x40, 0x5c, 0xe6, 0xeb, 0x60, 0x13, 0x7b, 0x79, 0x00, 0xfd, 0x80, 0x08, 0xe2, 0x75,
	0x81, 0x07, 0x04, 0xab, 0x56, 0x40, 0x3b, 0xb1, 0x19, 0x43, 0x51, 0x7f, 0x55, 0x1a, 0x35, 0xac,
	0x98, 0x47, 0xa5, 0x22, 0x5e, 0x10, 0x06, 0xe4, 0xa6, 0x21, 0x7a, 0xd0, 0xe6, 0x76, 0x5f, 0x57,
	0xb0, 0xe9, 0x7a, 0x83, 0x4a, 0x95, 0x7b, 0x0e, 0xa7, 0x7a, 0x76, 0x65, 0xc0, 0x7d, 0x49, 0xd1,
	0x1d, 0x38, 0x1c, 0x32, 0x49, 0x82, 0x2c, 0xc8, 0x8f, 0x16, 0x2f, 0x59, 0x7f, 0x6e, 0xa5, 0x15,
	0xe6, 0x97, 0x46, 0x76, 0xf6, 0x32, 0x91, 0x77, 0x3f, 0x3e, 0x16, 0x80, 0x6d, 0x00, 0x72, 0xaf,
	0x01, 0x9c, 0xd1, 0x25, 0x96, 0xa8, 0x5a, 0x69, 0xe7, 0xd8, 0x26, 0xc7, 0x50, 0x40, 0x93, 0x30,
	0xe6, 0x30, 0x47, 0x17, 0x1a, 0xb1, 0xdb, 0x4b, 0x74, 0x11, 0x8e, 0x93, 0xaa, 0x62, 0x4d, 0x5a,
	0x76, 0x6b, 0x65, 0xee, 0xd7, 0x5b, 0xc9, 0x68, 0x16, 0xe4, 0xe3, 0xf6, 0xbf, 0xe1, 0xee, 0x52,
	0xed, 0x9e, 0x5f, 0x6f, 0xa1, 0x59, 0x88, 0x02, 0x41, 0x6b, 0x54, 0x08, 0xea, 0x94, 0xeb, 0xc4,
	0x77, 0x1b, 0xc4, 0xa5, 0xc9, 0x98, 0x86, 0x49, 0x74, 0x4f, 0x96, 0xcd, 0x41, 0xee, 0x73, 0x14,
	0x5e, 0xe8, 0xc3, 0xc3, 0x88, 0x5e, 0x81, 0xe3, 0x5a, 0x54, 0xb9, 0xa3, 0xca, 0x88, 0x9f, 0x1d,
	0x24, 0xbe, 0x17, 0x6e, 0x4c, 0x1d, 0xfd, 0x44, 0x4f, 0x61, 0xbc, 0x49, 0x85, 0x6c, 0xfb, 0x25,
	0x19, 0xcd, 0xc6, 0xf2, 0xa3, 0xc5, 0xab, 0x83, 0xf0, 0x96, 0x78, 0x93, 0x0a, 0x9f, 0xf8, 0x55,
	0x7a, 0x5b, 0x10, 0x8f, 0xbe, 0xe0, 0x62, 0xed, 0x51, 0x08, 0x51, 0x1a, 0x6a, 0x37, 0xd8, 0xee,
	0x22, 0xa2, 0x32, 0x1c, 0x71, 0x78, 0xb5, 0xe1, 0x51, 0x5f, 0xc9, 0x64, 0x4c, 0xc3, 0x2f, 0x9c,
	0x03, 0xfe, 0x96, 0xc1, 0x30, 0xf8, 0xbf, 0x30, 0x73, 0x87, 0x00, 0x66, 0x74, 0xdb, 0x96, 0x99,
	0xec, 0xe9, 0x1b, 0xa3, 0x1d, 0x13, 0xa1, 0x45, 0x18, 0xf7, 0xb8, 0xc3, 0x6a, 0x8c, 0x3a, 0xa6,
	0x65, 0x29, 0x2b, 0xb4, 0xa3, 0xd5, 0xb1, 0xa3, 0xb5, 0xd2, 0xb1, 0x63, 0x29, 0xbe, 0xb3, 0x97,
	0x01, 0xdb, 0xdf, 0x32, 0xc0, 0xee, 0x66, 0xfd, 0x95, 0x1b, 0x47, 0x05, 0x98, 0x10, 0xe6, 0x6e,
	0xcb, 0x1e, 0xd9, 0x28, 0x4b, 0xb6, 0x49, 0x93, 0x43, 0x59, 0x90, 0x1f, 0xb3, 0x27, 0x3a, 0x07,
	0x77, 0xc9, 0xc6, 0x43, 0xb6, 0x49, 0x73, 0x5b, 0x00, 0x66, 0xfb, 0xcb, 0x34, 0x06, 0x79, 0x06,
	0x27, 0x7b, 0x0c, 0xc2, 0x68, 0x7b, 0x3e, 0x62, 0x67, 0xb6, 0x88, 0xe9, 0xf2, 0x84, 0xea, 0xad,
	0x53, 0x7c, 0x3b, 0x04, 0xff, 0xd1, 0x24, 0xd0, 0x07, 0x00, 0x87, 0xc3, 0x91, 0x42, 0xc5, 0x41,
	0xd0, 0xbf, 0x4f, 0x75, 0x6a, 0xfe, 0x4c, 0x39, 0xa1, 0xba, 0xdc, 0xc2, 0xd6, 0x97, 0xc3, 0x37,
	0xd1, 0x2b, 0x68, 0x1e, 0x87, 0xc9, 0xb3, 0x75, 0x52, 0x91, 0x9d, 0xf5, 0x80, 0x07, 0x0b, 0xbd,
	0x07, 0x70, 0xf2, 0xf8, 0x60, 0xa1, 0x6b, 0xa7, 0xa2, 0xd1, 0xe7, 0x5d, 0x48, 0x5d, 0x3f, 0x67,
	0xb6, 0x91, 0x33, 0xa3, 0xe5, 0xfc, 0x87, 0xa6, 0xb1, 0xa3, 0x04, 0x6e, 0xce, 0x61, 0x25, 0xb0,
	0x4b, 0x15, 0x7e, 0xe9, 0x30, 0xe7, 0x15, 0xfa, 0x04, 0xe0, 0xd4, 0x09, 0x57, 0x8d, 0x6e, 0x9e,
	0xaa, 0x68, 0xff, 0x59, 0x48, 0x2d, 0x9e, 0x1f, 0xc0, 0x10, 0xff, 0x5f, 0x13, 0x4f, 0xa0, 0x89,
	0x23, 0xc4, 0xeb, 0x4c, 0xaa, 0xd2, 0xe3, 0x9d, 0xfd, 0x34, 0xd8, 0xdd, 0x4f, 0x83, 0xef, 0xfb,
	0x69, 0xb0, 0x7d, 0x90, 0x8e, 0xec, 0x1e, 0xa4, 0x23, 0x5f, 0x0f, 0xd2, 0x91, 0x27, 0x37, 0x5c,
	0xa6, 0x56, 0x1b, 0x15, 0xab, 0xca, 0xbd, 0x01, 0x97, 0xb7, 0x71, 0xd2, 0x5f, 0x48, 0x65, 0x58,
	0x8f, 0xe9, 0xfc, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x5b, 0x78, 0x28, 0x5d, 0x07, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// GetTrustRegistry returns the trust registry information.
	GetTrustRegistry(ctx context.Context, in *QueryGetTrustRegistryRequest, opts ...grpc.CallOption) (*QueryGetTrustRegistryResponse, error)
	// ListTrustRegistries returns a list of Trust Registries
	ListTrustRegistries(ctx context.Context, in *QueryListTrustRegistriesRequest, opts ...grpc.CallOption) (*QueryListTrustRegistriesResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/veranablockchain.trustregistry.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetTrustRegistry(ctx context.Context, in *QueryGetTrustRegistryRequest, opts ...grpc.CallOption) (*QueryGetTrustRegistryResponse, error) {
	out := new(QueryGetTrustRegistryResponse)
	err := c.cc.Invoke(ctx, "/veranablockchain.trustregistry.Query/GetTrustRegistry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListTrustRegistries(ctx context.Context, in *QueryListTrustRegistriesRequest, opts ...grpc.CallOption) (*QueryListTrustRegistriesResponse, error) {
	out := new(QueryListTrustRegistriesResponse)
	err := c.cc.Invoke(ctx, "/veranablockchain.trustregistry.Query/ListTrustRegistries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// GetTrustRegistry returns the trust registry information.
	GetTrustRegistry(context.Context, *QueryGetTrustRegistryRequest) (*QueryGetTrustRegistryResponse, error)
	// ListTrustRegistries returns a list of Trust Registries
	ListTrustRegistries(context.Context, *QueryListTrustRegistriesRequest) (*QueryListTrustRegistriesResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GetTrustRegistry(ctx context.Context, req *QueryGetTrustRegistryRequest) (*QueryGetTrustRegistryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrustRegistry not implemented")
}
func (*UnimplementedQueryServer) ListTrustRegistries(ctx context.Context, req *QueryListTrustRegistriesRequest) (*QueryListTrustRegistriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTrustRegistries not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/veranablockchain.trustregistry.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetTrustRegistry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetTrustRegistryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetTrustRegistry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/veranablockchain.trustregistry.Query/GetTrustRegistry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetTrustRegistry(ctx, req.(*QueryGetTrustRegistryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListTrustRegistries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListTrustRegistriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListTrustRegistries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/veranablockchain.trustregistry.Query/ListTrustRegistries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListTrustRegistries(ctx, req.(*QueryListTrustRegistriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "veranablockchain.trustregistry.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetTrustRegistry",
			Handler:    _Query_GetTrustRegistry_Handler,
		},
		{
			MethodName: "ListTrustRegistries",
			Handler:    _Query_ListTrustRegistries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "veranablockchain/trustregistry/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetTrustRegistryRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetTrustRegistryRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetTrustRegistryRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PreferredLanguage) > 0 {
		i -= len(m.PreferredLanguage)
		copy(dAtA[i:], m.PreferredLanguage)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.PreferredLanguage)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ActiveGfOnly {
		i--
		if m.ActiveGfOnly {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetTrustRegistryResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetTrustRegistryResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetTrustRegistryResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Documents) > 0 {
		for iNdEx := len(m.Documents) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Documents[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Versions) > 0 {
		for iNdEx := len(m.Versions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Versions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.TrustRegistry != nil {
		{
			size, err := m.TrustRegistry.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListTrustRegistriesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListTrustRegistriesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListTrustRegistriesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ResponseMaxSize != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ResponseMaxSize))
		i--
		dAtA[i] = 0x20
	}
	if len(m.PreferredLanguage) > 0 {
		i -= len(m.PreferredLanguage)
		copy(dAtA[i:], m.PreferredLanguage)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.PreferredLanguage)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ActiveGfOnly {
		i--
		if m.ActiveGfOnly {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.Modified != nil {
		n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.Modified, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Modified):])
		if err3 != nil {
			return 0, err3
		}
		i -= n3
		i = encodeVarintQuery(dAtA, i, uint64(n3))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListTrustRegistriesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListTrustRegistriesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListTrustRegistriesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TrustRegistries) > 0 {
		for iNdEx := len(m.TrustRegistries) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TrustRegistries[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetTrustRegistryRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.ActiveGfOnly {
		n += 2
	}
	l = len(m.PreferredLanguage)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetTrustRegistryResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TrustRegistry != nil {
		l = m.TrustRegistry.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	if len(m.Versions) > 0 {
		for _, e := range m.Versions {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if len(m.Documents) > 0 {
		for _, e := range m.Documents {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryListTrustRegistriesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Modified != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Modified)
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.ActiveGfOnly {
		n += 2
	}
	l = len(m.PreferredLanguage)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.ResponseMaxSize != 0 {
		n += 1 + sovQuery(uint64(m.ResponseMaxSize))
	}
	return n
}

func (m *QueryListTrustRegistriesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.TrustRegistries) > 0 {
		for _, e := range m.TrustRegistries {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetTrustRegistryRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetTrustRegistryRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetTrustRegistryRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveGfOnly", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ActiveGfOnly = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreferredLanguage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PreferredLanguage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetTrustRegistryResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetTrustRegistryResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetTrustRegistryResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustRegistry", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TrustRegistry == nil {
				m.TrustRegistry = &TrustRegistry{}
			}
			if err := m.TrustRegistry.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Versions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Versions = append(m.Versions, GovernanceFrameworkVersion{})
			if err := m.Versions[len(m.Versions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Documents", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Documents = append(m.Documents, GovernanceFrameworkDocument{})
			if err := m.Documents[len(m.Documents)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListTrustRegistriesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListTrustRegistriesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListTrustRegistriesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Modified", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Modified == nil {
				m.Modified = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.Modified, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveGfOnly", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ActiveGfOnly = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreferredLanguage", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PreferredLanguage = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResponseMaxSize", wireType)
			}
			m.ResponseMaxSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ResponseMaxSize |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListTrustRegistriesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListTrustRegistriesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListTrustRegistriesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustRegistries", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TrustRegistries = append(m.TrustRegistries, TrustRegistry{})
			if err := m.TrustRegistries[len(m.TrustRegistries)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
