// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: veranablockchain/trustdeposit/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	TrustDepositReclaimBurnRate uint32 `protobuf:"varint,1,opt,name=trust_deposit_reclaim_burn_rate,json=trustDepositReclaimBurnRate,proto3" json:"trust_deposit_reclaim_burn_rate,omitempty"`
	TrustDepositShareValue      uint64 `protobuf:"varint,2,opt,name=trust_deposit_share_value,json=trustDepositShareValue,proto3" json:"trust_deposit_share_value,omitempty"`
	TrustDepositRate            uint32 `protobuf:"varint,3,opt,name=trust_deposit_rate,json=trustDepositRate,proto3" json:"trust_deposit_rate,omitempty"`
	WalletUserAgentRewardRate   uint32 `protobuf:"varint,4,opt,name=wallet_user_agent_reward_rate,json=walletUserAgentRewardRate,proto3" json:"wallet_user_agent_reward_rate,omitempty"`
	UserAgentRewardRate         uint32 `protobuf:"varint,5,opt,name=user_agent_reward_rate,json=userAgentRewardRate,proto3" json:"user_agent_reward_rate,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_54da5875c1c486fc, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetTrustDepositReclaimBurnRate() uint32 {
	if m != nil {
		return m.TrustDepositReclaimBurnRate
	}
	return 0
}

func (m *Params) GetTrustDepositShareValue() uint64 {
	if m != nil {
		return m.TrustDepositShareValue
	}
	return 0
}

func (m *Params) GetTrustDepositRate() uint32 {
	if m != nil {
		return m.TrustDepositRate
	}
	return 0
}

func (m *Params) GetWalletUserAgentRewardRate() uint32 {
	if m != nil {
		return m.WalletUserAgentRewardRate
	}
	return 0
}

func (m *Params) GetUserAgentRewardRate() uint32 {
	if m != nil {
		return m.UserAgentRewardRate
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "veranablockchain.trustdeposit.Params")
}

func init() {
	proto.RegisterFile("veranablockchain/trustdeposit/params.proto", fileDescriptor_54da5875c1c486fc)
}

var fileDescriptor_54da5875c1c486fc = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x86, 0x3b, 0xfd, 0xfa, 0x75, 0x31, 0x20, 0x68, 0x94, 0xd2, 0x56, 0x9a, 0x16, 0x17, 0x52,
	0x8a, 0x36, 0x8b, 0xae, 0x14, 0x04, 0x2d, 0xbd, 0x00, 0x89, 0xa8, 0xe0, 0x66, 0x38, 0x49, 0x87,
	0x34, 0x98, 0x64, 0xc2, 0xfc, 0xb4, 0x7a, 0x0b, 0xae, 0xbc, 0x04, 0x2f, 0xc1, 0xcb, 0x70, 0xd9,
	0xa5, 0x3b, 0xa5, 0x5d, 0xe8, 0x65, 0xc8, 0xcc, 0x28, 0xf4, 0x87, 0x6e, 0xc2, 0x21, 0xf3, 0xbc,
	0xcf, 0x3b, 0xcc, 0xc1, 0x9d, 0x31, 0xe5, 0x90, 0x41, 0x90, 0xb0, 0xf0, 0x3e, 0x1c, 0x41, 0x9c,
	0x79, 0x92, 0x2b, 0x21, 0x87, 0x34, 0x67, 0x22, 0x96, 0x5e, 0x0e, 0x1c, 0x52, 0xd1, 0xcd, 0x39,
	0x93, 0xcc, 0x69, 0xac, 0xb2, 0xdd, 0x45, 0xb6, 0xbe, 0x03, 0x69, 0x9c, 0x31, 0xcf, 0x7c, 0x6d,
	0xa2, 0xbe, 0x17, 0xb1, 0x88, 0x99, 0xd1, 0xd3, 0x93, 0xfd, 0x7b, 0xf0, 0x51, 0xc4, 0xe5, 0x4b,
	0x23, 0x76, 0x06, 0xb8, 0x69, 0x1c, 0xe4, 0x57, 0x42, 0x38, 0x0d, 0x13, 0x88, 0x53, 0x12, 0x28,
	0x9e, 0x11, 0x0e, 0x92, 0x56, 0x51, 0x0b, 0xb5, 0xb7, 0xfc, 0x7d, 0x83, 0x0d, 0x2c, 0xe5, 0x5b,
	0xa8, 0xaf, 0x78, 0xe6, 0x83, 0xa4, 0xce, 0x09, 0xae, 0x2d, 0x5b, 0xc4, 0x08, 0x38, 0x25, 0x63,
	0x48, 0x14, 0xad, 0x16, 0x5b, 0xa8, 0x5d, 0xf2, 0x2b, 0x8b, 0xf9, 0x2b, 0x7d, 0x7c, 0xa3, 0x4f,
	0x9d, 0x23, 0xec, 0xac, 0x5c, 0x40, 0x77, 0xfe, 0x33, 0x9d, 0xdb, 0x4b, 0x9d, 0xba, 0xe8, 0x1c,
	0x37, 0x26, 0x90, 0x24, 0x54, 0x12, 0x25, 0x28, 0x27, 0x10, 0xd1, 0x4c, 0x5f, 0x79, 0x02, 0x7c,
	0x68, 0x83, 0x25, 0x13, 0xac, 0x59, 0xe8, 0x5a, 0x50, 0x7e, 0xa1, 0x11, 0xdf, 0x10, 0xc6, 0xd0,
	0xc3, 0x95, 0x0d, 0xd1, 0xff, 0x26, 0xba, 0xab, 0xd6, 0x43, 0xa7, 0xde, 0xf7, 0x4b, 0x13, 0x3d,
	0x7d, 0xbd, 0x76, 0x0e, 0xd7, 0xb6, 0xf5, 0xb0, 0xbc, 0x2f, 0xfb, 0xac, 0xfd, 0xdb, 0xb7, 0x99,
	0x8b, 0xa6, 0x33, 0x17, 0x7d, 0xce, 0x5c, 0xf4, 0x3c, 0x77, 0x0b, 0xd3, 0xb9, 0x5b, 0x78, 0x9f,
	0xbb, 0x85, 0xbb, 0xb3, 0x28, 0x96, 0x23, 0x15, 0x74, 0x43, 0x96, 0x7a, 0x56, 0x76, 0x9c, 0x40,
	0x20, 0xfe, 0xe6, 0xcd, 0x66, 0xf9, 0x98, 0x53, 0x11, 0x94, 0xcd, 0x06, 0x7b, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x14, 0x61, 0x12, 0xef, 0x37, 0x02, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TrustDepositReclaimBurnRate != that1.TrustDepositReclaimBurnRate {
		return false
	}
	if this.TrustDepositShareValue != that1.TrustDepositShareValue {
		return false
	}
	if this.TrustDepositRate != that1.TrustDepositRate {
		return false
	}
	if this.WalletUserAgentRewardRate != that1.WalletUserAgentRewardRate {
		return false
	}
	if this.UserAgentRewardRate != that1.UserAgentRewardRate {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.UserAgentRewardRate != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.UserAgentRewardRate))
		i--
		dAtA[i] = 0x28
	}
	if m.WalletUserAgentRewardRate != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.WalletUserAgentRewardRate))
		i--
		dAtA[i] = 0x20
	}
	if m.TrustDepositRate != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.TrustDepositRate))
		i--
		dAtA[i] = 0x18
	}
	if m.TrustDepositShareValue != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.TrustDepositShareValue))
		i--
		dAtA[i] = 0x10
	}
	if m.TrustDepositReclaimBurnRate != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.TrustDepositReclaimBurnRate))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TrustDepositReclaimBurnRate != 0 {
		n += 1 + sovParams(uint64(m.TrustDepositReclaimBurnRate))
	}
	if m.TrustDepositShareValue != 0 {
		n += 1 + sovParams(uint64(m.TrustDepositShareValue))
	}
	if m.TrustDepositRate != 0 {
		n += 1 + sovParams(uint64(m.TrustDepositRate))
	}
	if m.WalletUserAgentRewardRate != 0 {
		n += 1 + sovParams(uint64(m.WalletUserAgentRewardRate))
	}
	if m.UserAgentRewardRate != 0 {
		n += 1 + sovParams(uint64(m.UserAgentRewardRate))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustDepositReclaimBurnRate", wireType)
			}
			m.TrustDepositReclaimBurnRate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TrustDepositReclaimBurnRate |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustDepositShareValue", wireType)
			}
			m.TrustDepositShareValue = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TrustDepositShareValue |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustDepositRate", wireType)
			}
			m.TrustDepositRate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TrustDepositRate |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WalletUserAgentRewardRate", wireType)
			}
			m.WalletUserAgentRewardRate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WalletUserAgentRewardRate |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserAgentRewardRate", wireType)
			}
			m.UserAgentRewardRate = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UserAgentRewardRate |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
