// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: veranablockchain/diddirectory/query.proto

package types

import (
	context "context"
	fmt "fmt"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"

	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/timestamppb"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4c4a32fec548b8c, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4c4a32fec548b8c, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryListDIDsRequest struct {
	Account         string     `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Changed         *time.Time `protobuf:"bytes,2,opt,name=changed,proto3,stdtime" json:"changed,omitempty"`
	Expired         bool       `protobuf:"varint,3,opt,name=expired,proto3" json:"expired,omitempty"`
	OverGrace       bool       `protobuf:"varint,4,opt,name=over_grace,json=overGrace,proto3" json:"over_grace,omitempty"`
	ResponseMaxSize uint32     `protobuf:"varint,5,opt,name=response_max_size,json=responseMaxSize,proto3" json:"response_max_size,omitempty"`
}

func (m *QueryListDIDsRequest) Reset()         { *m = QueryListDIDsRequest{} }
func (m *QueryListDIDsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListDIDsRequest) ProtoMessage()    {}
func (*QueryListDIDsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4c4a32fec548b8c, []int{2}
}
func (m *QueryListDIDsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListDIDsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListDIDsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListDIDsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListDIDsRequest.Merge(m, src)
}
func (m *QueryListDIDsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListDIDsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListDIDsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListDIDsRequest proto.InternalMessageInfo

func (m *QueryListDIDsRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *QueryListDIDsRequest) GetChanged() *time.Time {
	if m != nil {
		return m.Changed
	}
	return nil
}

func (m *QueryListDIDsRequest) GetExpired() bool {
	if m != nil {
		return m.Expired
	}
	return false
}

func (m *QueryListDIDsRequest) GetOverGrace() bool {
	if m != nil {
		return m.OverGrace
	}
	return false
}

func (m *QueryListDIDsRequest) GetResponseMaxSize() uint32 {
	if m != nil {
		return m.ResponseMaxSize
	}
	return 0
}

type QueryListDIDsResponse struct {
	Dids []DIDDirectory `protobuf:"bytes,1,rep,name=dids,proto3" json:"dids"`
}

func (m *QueryListDIDsResponse) Reset()         { *m = QueryListDIDsResponse{} }
func (m *QueryListDIDsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListDIDsResponse) ProtoMessage()    {}
func (*QueryListDIDsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4c4a32fec548b8c, []int{3}
}
func (m *QueryListDIDsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListDIDsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListDIDsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListDIDsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListDIDsResponse.Merge(m, src)
}
func (m *QueryListDIDsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListDIDsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListDIDsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListDIDsResponse proto.InternalMessageInfo

func (m *QueryListDIDsResponse) GetDids() []DIDDirectory {
	if m != nil {
		return m.Dids
	}
	return nil
}

type QueryGetDIDRequest struct {
	Did string `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
}

func (m *QueryGetDIDRequest) Reset()         { *m = QueryGetDIDRequest{} }
func (m *QueryGetDIDRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetDIDRequest) ProtoMessage()    {}
func (*QueryGetDIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4c4a32fec548b8c, []int{4}
}
func (m *QueryGetDIDRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDIDRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDIDRequest.Merge(m, src)
}
func (m *QueryGetDIDRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDIDRequest proto.InternalMessageInfo

func (m *QueryGetDIDRequest) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

type QueryGetDIDResponse struct {
	DidEntry DIDDirectory `protobuf:"bytes,1,opt,name=did_entry,json=didEntry,proto3" json:"did_entry"`
}

func (m *QueryGetDIDResponse) Reset()         { *m = QueryGetDIDResponse{} }
func (m *QueryGetDIDResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetDIDResponse) ProtoMessage()    {}
func (*QueryGetDIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b4c4a32fec548b8c, []int{5}
}
func (m *QueryGetDIDResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetDIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetDIDResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetDIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetDIDResponse.Merge(m, src)
}
func (m *QueryGetDIDResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetDIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetDIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetDIDResponse proto.InternalMessageInfo

func (m *QueryGetDIDResponse) GetDidEntry() DIDDirectory {
	if m != nil {
		return m.DidEntry
	}
	return DIDDirectory{}
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "veranablockchain.diddirectory.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "veranablockchain.diddirectory.QueryParamsResponse")
	proto.RegisterType((*QueryListDIDsRequest)(nil), "veranablockchain.diddirectory.QueryListDIDsRequest")
	proto.RegisterType((*QueryListDIDsResponse)(nil), "veranablockchain.diddirectory.QueryListDIDsResponse")
	proto.RegisterType((*QueryGetDIDRequest)(nil), "veranablockchain.diddirectory.QueryGetDIDRequest")
	proto.RegisterType((*QueryGetDIDResponse)(nil), "veranablockchain.diddirectory.QueryGetDIDResponse")
}

func init() {
	proto.RegisterFile("veranablockchain/diddirectory/query.proto", fileDescriptor_b4c4a32fec548b8c)
}

var fileDescriptor_b4c4a32fec548b8c = []byte{
	// 673 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4f, 0x6b, 0x13, 0x4f,
	0x18, 0xce, 0x36, 0x6d, 0x9a, 0x4c, 0x29, 0x6d, 0xa7, 0x29, 0xec, 0x2f, 0xfc, 0x9a, 0x94, 0x05,
	0x25, 0x56, 0xba, 0x43, 0x52, 0xaf, 0x0a, 0x86, 0x94, 0x5a, 0x50, 0xd1, 0xad, 0x20, 0x78, 0x30,
	0x4c, 0x76, 0xc6, 0xed, 0x60, 0x76, 0x67, 0xbb, 0x33, 0x09, 0x49, 0xc5, 0x8b, 0x07, 0x41, 0x4f,
	0x05, 0xbf, 0x84, 0xde, 0x3c, 0xf8, 0x21, 0x7a, 0x2c, 0x7a, 0xf1, 0x54, 0xa5, 0x15, 0x3c, 0xfa,
	0x15, 0x64, 0x67, 0x67, 0xa0, 0xad, 0xd2, 0x3f, 0x5e, 0x96, 0x99, 0xf7, 0x7d, 0xde, 0xf7, 0x79,
	0xe6, 0x79, 0x67, 0x07, 0x5c, 0x1b, 0xd0, 0x04, 0x47, 0xb8, 0xdb, 0xe3, 0xfe, 0x73, 0x7f, 0x0b,
	0xb3, 0x08, 0x11, 0x46, 0x08, 0x4b, 0xa8, 0x2f, 0x79, 0x32, 0x42, 0xdb, 0x7d, 0x9a, 0x8c, 0xdc,
	0x38, 0xe1, 0x92, 0xc3, 0xc5, 0xd3, 0x50, 0xf7, 0x38, 0xb4, 0x32, 0x87, 0x43, 0x16, 0x71, 0xa4,
	0xbe, 0x59, 0x45, 0xa5, 0x1c, 0xf0, 0x80, 0xab, 0x25, 0x4a, 0x57, 0x3a, 0xfa, 0x7f, 0xc0, 0x79,
	0xd0, 0xa3, 0x08, 0xc7, 0x0c, 0xe1, 0x28, 0xe2, 0x12, 0x4b, 0xc6, 0x23, 0xa1, 0xb3, 0xcb, 0x3e,
	0x17, 0x21, 0x17, 0xa8, 0x8b, 0x05, 0xcd, 0xe8, 0xd1, 0xa0, 0xd1, 0xa5, 0x12, 0x37, 0x50, 0x8c,
	0x03, 0x16, 0x29, 0xb0, 0xc1, 0x9e, 0x2d, 0x3e, 0xc6, 0x09, 0x0e, 0x4d, 0xdf, 0x9a, 0x66, 0x55,
	0xbb, 0x6e, 0xff, 0x19, 0x92, 0x2c, 0xa4, 0x42, 0xe2, 0x30, 0xd6, 0x80, 0xff, 0x32, 0xe2, 0x4e,
	0xa6, 0x37, 0xdb, 0xe8, 0xd4, 0x39, 0x26, 0xc9, 0x51, 0x4c, 0x35, 0xd4, 0x29, 0x03, 0xf8, 0x30,
	0x15, 0xfd, 0x40, 0x71, 0x7b, 0x74, 0xbb, 0x4f, 0x85, 0x74, 0x3a, 0x60, 0xfe, 0x44, 0x54, 0xc4,
	0x3c, 0x12, 0x14, 0xde, 0x01, 0x85, 0x4c, 0xa3, 0x6d, 0x2d, 0x59, 0xf5, 0xa9, 0xe6, 0x15, 0xf7,
	0x4c, 0x8b, 0xdd, 0xac, 0xbc, 0x55, 0xda, 0x3b, 0xa8, 0xe5, 0xde, 0xff, 0xfc, 0xb8, 0x6c, 0x79,
	0xba, 0xde, 0xf9, 0x65, 0x81, 0xb2, 0x62, 0xb8, 0xcb, 0x84, 0x6c, 0x6f, 0xb4, 0x0d, 0x33, 0x6c,
	0x82, 0x49, 0xec, 0xfb, 0xbc, 0x1f, 0x49, 0xc5, 0x51, 0x6a, 0xd9, 0x9f, 0x3f, 0xad, 0x94, 0xf5,
	0xe9, 0x6e, 0x13, 0x92, 0x50, 0x21, 0x36, 0x65, 0xc2, 0xa2, 0xc0, 0x33, 0x40, 0x78, 0x0b, 0x4c,
	0xfa, 0x5b, 0x38, 0x0a, 0x28, 0xb1, 0xc7, 0x94, 0xae, 0x8a, 0x9b, 0x99, 0xe7, 0x1a, 0xf3, 0xdc,
	0x47, 0xc6, 0xbc, 0x56, 0x71, 0xef, 0xa0, 0x66, 0xed, 0x7e, 0xab, 0x59, 0x9e, 0x29, 0x82, 0x36,
	0x98, 0xa4, 0xc3, 0x98, 0x25, 0x94, 0xd8, 0xf9, 0x25, 0xab, 0x5e, 0xf4, 0xcc, 0x16, 0x2e, 0x02,
	0xc0, 0x07, 0x34, 0xe9, 0x04, 0x09, 0xf6, 0xa9, 0x3d, 0xae, 0x92, 0xa5, 0x34, 0xb2, 0x9e, 0x06,
	0xe0, 0x32, 0x98, 0x4b, 0xb4, 0x37, 0x9d, 0x10, 0x0f, 0x3b, 0x82, 0xed, 0x50, 0x7b, 0x62, 0xc9,
	0xaa, 0x4f, 0x7b, 0x33, 0x26, 0x71, 0x0f, 0x0f, 0x37, 0xd9, 0x0e, 0x75, 0x9e, 0x82, 0x85, 0x53,
	0x07, 0xd6, 0xa6, 0xae, 0x81, 0x71, 0xc2, 0x48, 0x6a, 0x69, 0xbe, 0x3e, 0xd5, 0xbc, 0x7e, 0x8e,
	0xa5, 0xed, 0x8d, 0x76, 0xdb, 0x6c, 0x5a, 0xe3, 0xa9, 0xb1, 0x9e, 0x2a, 0x77, 0xae, 0xea, 0x41,
	0xae, 0xd3, 0xb4, 0xbd, 0xb1, 0x73, 0x16, 0xe4, 0x09, 0x23, 0x99, 0x95, 0x5e, 0xba, 0x74, 0xa8,
	0x1e, 0xad, 0xc1, 0x69, 0x15, 0xf7, 0x41, 0x89, 0x30, 0xd2, 0xa1, 0x91, 0x4c, 0x46, 0x7a, 0xba,
	0xff, 0x20, 0xa5, 0x48, 0x18, 0x59, 0x4b, 0x5b, 0x34, 0x3f, 0xe4, 0xc1, 0x84, 0xe2, 0x81, 0xaf,
	0x2d, 0x50, 0xc8, 0x2e, 0x02, 0x6c, 0x9c, 0xd3, 0xf1, 0xcf, 0x9b, 0x58, 0x69, 0x5e, 0xa6, 0x24,
	0x3b, 0x8b, 0xb3, 0xf0, 0xea, 0xcb, 0x8f, 0x77, 0x63, 0x33, 0x70, 0x1a, 0x11, 0x82, 0x06, 0x0d,
	0xfd, 0x5f, 0xc1, 0xb7, 0x16, 0x28, 0x1a, 0xf7, 0xe1, 0xea, 0x45, 0xfa, 0x9e, 0xba, 0x9c, 0x95,
	0x1b, 0x97, 0x2b, 0xd2, 0x72, 0xe6, 0x95, 0x9c, 0x69, 0x38, 0xa5, 0xe5, 0xf4, 0x98, 0x90, 0xf0,
	0x8d, 0x05, 0x0a, 0xd9, 0x08, 0x2e, 0xe6, 0xca, 0x89, 0xb1, 0x5e, 0xcc, 0x95, 0x93, 0x13, 0x76,
	0x6c, 0x25, 0x03, 0xc2, 0x59, 0x2d, 0x23, 0xa0, 0x12, 0xbd, 0x20, 0x8c, 0xbc, 0x6c, 0x3d, 0xde,
	0x3b, 0xac, 0x5a, 0xfb, 0x87, 0x55, 0xeb, 0xfb, 0x61, 0xd5, 0xda, 0x3d, 0xaa, 0xe6, 0xf6, 0x8f,
	0xaa, 0xb9, 0xaf, 0x47, 0xd5, 0xdc, 0x93, 0x9b, 0x01, 0x93, 0x5b, 0xfd, 0xae, 0xeb, 0xf3, 0x10,
	0x65, 0x8c, 0x2b, 0x3d, 0xdc, 0x15, 0x66, 0x7d, 0xec, 0x81, 0x19, 0xfe, 0xe5, 0x89, 0xe9, 0x16,
	0xd4, 0xff, 0xb7, 0xfa, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xf6, 0x15, 0xd9, 0xcb, 0xb5, 0x05, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	ListDIDs(ctx context.Context, in *QueryListDIDsRequest, opts ...grpc.CallOption) (*QueryListDIDsResponse, error)
	GetDID(ctx context.Context, in *QueryGetDIDRequest, opts ...grpc.CallOption) (*QueryGetDIDResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/veranablockchain.diddirectory.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListDIDs(ctx context.Context, in *QueryListDIDsRequest, opts ...grpc.CallOption) (*QueryListDIDsResponse, error) {
	out := new(QueryListDIDsResponse)
	err := c.cc.Invoke(ctx, "/veranablockchain.diddirectory.Query/ListDIDs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetDID(ctx context.Context, in *QueryGetDIDRequest, opts ...grpc.CallOption) (*QueryGetDIDResponse, error) {
	out := new(QueryGetDIDResponse)
	err := c.cc.Invoke(ctx, "/veranablockchain.diddirectory.Query/GetDID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	ListDIDs(context.Context, *QueryListDIDsRequest) (*QueryListDIDsResponse, error)
	GetDID(context.Context, *QueryGetDIDRequest) (*QueryGetDIDResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) ListDIDs(ctx context.Context, req *QueryListDIDsRequest) (*QueryListDIDsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDIDs not implemented")
}
func (*UnimplementedQueryServer) GetDID(ctx context.Context, req *QueryGetDIDRequest) (*QueryGetDIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDID not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/veranablockchain.diddirectory.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListDIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListDIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListDIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/veranablockchain.diddirectory.Query/ListDIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListDIDs(ctx, req.(*QueryListDIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetDID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetDIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetDID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/veranablockchain.diddirectory.Query/GetDID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetDID(ctx, req.(*QueryGetDIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "veranablockchain.diddirectory.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "ListDIDs",
			Handler:    _Query_ListDIDs_Handler,
		},
		{
			MethodName: "GetDID",
			Handler:    _Query_GetDID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "veranablockchain/diddirectory/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryListDIDsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListDIDsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListDIDsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ResponseMaxSize != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ResponseMaxSize))
		i--
		dAtA[i] = 0x28
	}
	if m.OverGrace {
		i--
		if m.OverGrace {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.Expired {
		i--
		if m.Expired {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.Changed != nil {
		n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.Changed, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Changed):])
		if err2 != nil {
			return 0, err2
		}
		i -= n2
		i = encodeVarintQuery(dAtA, i, uint64(n2))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListDIDsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListDIDsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListDIDsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Dids) > 0 {
		for iNdEx := len(m.Dids) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Dids[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDIDRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDIDRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDIDRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetDIDResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetDIDResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetDIDResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.DidEntry.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryListDIDsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Changed != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Changed)
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Expired {
		n += 2
	}
	if m.OverGrace {
		n += 2
	}
	if m.ResponseMaxSize != 0 {
		n += 1 + sovQuery(uint64(m.ResponseMaxSize))
	}
	return n
}

func (m *QueryListDIDsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Dids) > 0 {
		for _, e := range m.Dids {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryGetDIDRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetDIDResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.DidEntry.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListDIDsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListDIDsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListDIDsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Changed", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Changed == nil {
				m.Changed = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.Changed, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Expired", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Expired = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OverGrace", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OverGrace = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResponseMaxSize", wireType)
			}
			m.ResponseMaxSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ResponseMaxSize |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListDIDsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListDIDsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListDIDsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dids", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Dids = append(m.Dids, DIDDirectory{})
			if err := m.Dids[len(m.Dids)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDIDRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDIDRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDIDRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetDIDResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetDIDResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetDIDResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DidEntry", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DidEntry.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
