// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: verana/credentialschema/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	CredentialSchemaTrustDeposit                                   uint64 `protobuf:"varint,1,opt,name=credential_schema_trust_deposit,json=credentialSchemaTrustDeposit,proto3" json:"credential_schema_trust_deposit,omitempty"`
	CredentialSchemaSchemaMaxSize                                  uint64 `protobuf:"varint,2,opt,name=credential_schema_schema_max_size,json=credentialSchemaSchemaMaxSize,proto3" json:"credential_schema_schema_max_size,omitempty"`
	CredentialSchemaIssuerGrantorValidationValidityPeriodMaxDays   uint32 `protobuf:"varint,3,opt,name=credential_schema_issuer_grantor_validation_validity_period_max_days,json=credentialSchemaIssuerGrantorValidationValidityPeriodMaxDays,proto3" json:"credential_schema_issuer_grantor_validation_validity_period_max_days,omitempty"`
	CredentialSchemaVerifierGrantorValidationValidityPeriodMaxDays uint32 `protobuf:"varint,4,opt,name=credential_schema_verifier_grantor_validation_validity_period_max_days,json=credentialSchemaVerifierGrantorValidationValidityPeriodMaxDays,proto3" json:"credential_schema_verifier_grantor_validation_validity_period_max_days,omitempty"`
	CredentialSchemaIssuerValidationValidityPeriodMaxDays          uint32 `protobuf:"varint,5,opt,name=credential_schema_issuer_validation_validity_period_max_days,json=credentialSchemaIssuerValidationValidityPeriodMaxDays,proto3" json:"credential_schema_issuer_validation_validity_period_max_days,omitempty"`
	CredentialSchemaVerifierValidationValidityPeriodMaxDays        uint32 `protobuf:"varint,6,opt,name=credential_schema_verifier_validation_validity_period_max_days,json=credentialSchemaVerifierValidationValidityPeriodMaxDays,proto3" json:"credential_schema_verifier_validation_validity_period_max_days,omitempty"`
	CredentialSchemaHolderValidationValidityPeriodMaxDays          uint32 `protobuf:"varint,7,opt,name=credential_schema_holder_validation_validity_period_max_days,json=credentialSchemaHolderValidationValidityPeriodMaxDays,proto3" json:"credential_schema_holder_validation_validity_period_max_days,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_01d2f22515c811b9, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetCredentialSchemaTrustDeposit() uint64 {
	if m != nil {
		return m.CredentialSchemaTrustDeposit
	}
	return 0
}

func (m *Params) GetCredentialSchemaSchemaMaxSize() uint64 {
	if m != nil {
		return m.CredentialSchemaSchemaMaxSize
	}
	return 0
}

func (m *Params) GetCredentialSchemaIssuerGrantorValidationValidityPeriodMaxDays() uint32 {
	if m != nil {
		return m.CredentialSchemaIssuerGrantorValidationValidityPeriodMaxDays
	}
	return 0
}

func (m *Params) GetCredentialSchemaVerifierGrantorValidationValidityPeriodMaxDays() uint32 {
	if m != nil {
		return m.CredentialSchemaVerifierGrantorValidationValidityPeriodMaxDays
	}
	return 0
}

func (m *Params) GetCredentialSchemaIssuerValidationValidityPeriodMaxDays() uint32 {
	if m != nil {
		return m.CredentialSchemaIssuerValidationValidityPeriodMaxDays
	}
	return 0
}

func (m *Params) GetCredentialSchemaVerifierValidationValidityPeriodMaxDays() uint32 {
	if m != nil {
		return m.CredentialSchemaVerifierValidationValidityPeriodMaxDays
	}
	return 0
}

func (m *Params) GetCredentialSchemaHolderValidationValidityPeriodMaxDays() uint32 {
	if m != nil {
		return m.CredentialSchemaHolderValidationValidityPeriodMaxDays
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "verana.credentialschema.Params")
}

func init() {
	proto.RegisterFile("verana/credentialschema/params.proto", fileDescriptor_01d2f22515c811b9)
}

var fileDescriptor_01d2f22515c811b9 = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xc1, 0xaa, 0xd3, 0x40,
	0x14, 0x86, 0x3b, 0x7a, 0x8d, 0x30, 0xe0, 0xc2, 0x20, 0x58, 0x2e, 0x9a, 0x5b, 0xc5, 0x45, 0x15,
	0x6c, 0x16, 0x22, 0x82, 0x94, 0x82, 0x52, 0xb5, 0x2e, 0x0a, 0xa5, 0x95, 0x2e, 0x74, 0x11, 0x4e,
	0x92, 0x31, 0x19, 0x4c, 0x32, 0x61, 0x66, 0x5a, 0x92, 0xba, 0x70, 0xdf, 0x85, 0xf8, 0x08, 0x3e,
	0x82, 0x8f, 0xe1, 0xb2, 0x4b, 0x37, 0x82, 0xb4, 0x0b, 0x7d, 0x0c, 0xe9, 0x4c, 0xb4, 0x90, 0xb4,
	0x36, 0xde, 0xcd, 0xe4, 0x10, 0x7e, 0xbe, 0xff, 0x3f, 0x07, 0x7e, 0x7c, 0x67, 0x4e, 0x38, 0x24,
	0x60, 0x7b, 0x9c, 0xf8, 0x24, 0x91, 0x14, 0x22, 0xe1, 0x85, 0x24, 0x06, 0x3b, 0x05, 0x0e, 0xb1,
	0xe8, 0xa4, 0x9c, 0x49, 0x66, 0x5e, 0xd7, 0xaa, 0x4e, 0x59, 0x75, 0x7a, 0x15, 0x62, 0x9a, 0x30,
	0x5b, 0xbd, 0x5a, 0x7b, 0x7a, 0x2d, 0x60, 0x01, 0x53, 0xa3, 0xbd, 0x9d, 0xf4, 0xdf, 0xdb, 0xdf,
	0x0d, 0x6c, 0x8c, 0x14, 0xd2, 0x7c, 0x86, 0xcf, 0x76, 0x1c, 0x47, 0x83, 0x1c, 0xc9, 0x67, 0x42,
	0x3a, 0x3e, 0x49, 0x99, 0xa0, 0xb2, 0x89, 0x5a, 0xa8, 0x7d, 0x32, 0xbe, 0xb1, 0x93, 0x4d, 0x94,
	0xea, 0xd5, 0x56, 0xd4, 0xd7, 0x1a, 0x73, 0x80, 0x6f, 0x55, 0x31, 0xc5, 0x27, 0x86, 0xcc, 0x11,
	0x74, 0x41, 0x9a, 0x17, 0x14, 0xe8, 0x66, 0x19, 0xa4, 0xdf, 0x21, 0x64, 0x13, 0xba, 0x20, 0xe6,
	0x12, 0xe1, 0x7e, 0x15, 0x45, 0x85, 0x98, 0x11, 0xee, 0x04, 0x1c, 0x12, 0xc9, 0xb8, 0x33, 0x87,
	0x88, 0xfa, 0x20, 0x29, 0x4b, 0xf4, 0x48, 0x65, 0xee, 0xa4, 0x84, 0x53, 0xe6, 0x2b, 0x37, 0x1f,
	0x72, 0xd1, 0xbc, 0xd8, 0x42, 0xed, 0x2b, 0xe3, 0x6e, 0xd9, 0xed, 0xa5, 0x22, 0xbd, 0xd0, 0xa0,
	0xe9, 0x5f, 0xce, 0xb4, 0xc0, 0x8c, 0x14, 0x65, 0x08, 0x59, 0x1f, 0x72, 0x61, 0x7e, 0x44, 0xf8,
	0x79, 0x35, 0xcc, 0x9c, 0x70, 0xfa, 0x96, 0xfe, 0x67, 0x9c, 0x13, 0x15, 0xa7, 0x57, 0x8e, 0x33,
	0x2d, 0x58, 0x35, 0x03, 0xbd, 0xc7, 0xdd, 0x83, 0xc7, 0xa9, 0x93, 0xe2, 0x92, 0x4a, 0xf1, 0x70,
	0xff, 0x51, 0x8e, 0x99, 0x7f, 0xc0, 0xbd, 0x7f, 0x1c, 0xa3, 0x8e, 0xbd, 0xa1, 0xec, 0x1f, 0x1d,
	0x3a, 0xc2, 0xb9, 0xb6, 0x0f, 0x59, 0xe4, 0xd7, 0xb4, 0xbf, 0xbc, 0x7f, 0xfb, 0x81, 0x22, 0x1c,
	0x31, 0x7f, 0x7c, 0xf7, 0xd7, 0xe7, 0x33, 0xb4, 0xfc, 0xf9, 0xe5, 0x5e, 0xab, 0x68, 0x69, 0x56,
	0xed, 0xa9, 0x2e, 0xd5, 0xd3, 0x37, 0x5f, 0xd7, 0x16, 0x5a, 0xad, 0x2d, 0xf4, 0x63, 0x6d, 0xa1,
	0x4f, 0x1b, 0xab, 0xb1, 0xda, 0x58, 0x8d, 0x6f, 0x1b, 0xab, 0xf1, 0xfa, 0x49, 0x40, 0x65, 0x38,
	0x73, 0x3b, 0x1e, 0x8b, 0x6d, 0x8d, 0xb9, 0x1f, 0x81, 0x2b, 0xfe, 0xcc, 0x6e, 0xc4, 0xbc, 0x77,
	0x5e, 0x08, 0x34, 0xd9, 0x47, 0x97, 0x79, 0x4a, 0x84, 0x6b, 0xa8, 0x0e, 0x3f, 0xf8, 0x1d, 0x00,
	0x00, 0xff, 0xff, 0x28, 0xc2, 0x89, 0x09, 0x2d, 0x04, 0x00, 0x00,
}

func (this *Params) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Params)
	if !ok {
		that2, ok := that.(Params)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.CredentialSchemaTrustDeposit != that1.CredentialSchemaTrustDeposit {
		return false
	}
	if this.CredentialSchemaSchemaMaxSize != that1.CredentialSchemaSchemaMaxSize {
		return false
	}
	if this.CredentialSchemaIssuerGrantorValidationValidityPeriodMaxDays != that1.CredentialSchemaIssuerGrantorValidationValidityPeriodMaxDays {
		return false
	}
	if this.CredentialSchemaVerifierGrantorValidationValidityPeriodMaxDays != that1.CredentialSchemaVerifierGrantorValidationValidityPeriodMaxDays {
		return false
	}
	if this.CredentialSchemaIssuerValidationValidityPeriodMaxDays != that1.CredentialSchemaIssuerValidationValidityPeriodMaxDays {
		return false
	}
	if this.CredentialSchemaVerifierValidationValidityPeriodMaxDays != that1.CredentialSchemaVerifierValidationValidityPeriodMaxDays {
		return false
	}
	if this.CredentialSchemaHolderValidationValidityPeriodMaxDays != that1.CredentialSchemaHolderValidationValidityPeriodMaxDays {
		return false
	}
	return true
}
func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CredentialSchemaHolderValidationValidityPeriodMaxDays != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.CredentialSchemaHolderValidationValidityPeriodMaxDays))
		i--
		dAtA[i] = 0x38
	}
	if m.CredentialSchemaVerifierValidationValidityPeriodMaxDays != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.CredentialSchemaVerifierValidationValidityPeriodMaxDays))
		i--
		dAtA[i] = 0x30
	}
	if m.CredentialSchemaIssuerValidationValidityPeriodMaxDays != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.CredentialSchemaIssuerValidationValidityPeriodMaxDays))
		i--
		dAtA[i] = 0x28
	}
	if m.CredentialSchemaVerifierGrantorValidationValidityPeriodMaxDays != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.CredentialSchemaVerifierGrantorValidationValidityPeriodMaxDays))
		i--
		dAtA[i] = 0x20
	}
	if m.CredentialSchemaIssuerGrantorValidationValidityPeriodMaxDays != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.CredentialSchemaIssuerGrantorValidationValidityPeriodMaxDays))
		i--
		dAtA[i] = 0x18
	}
	if m.CredentialSchemaSchemaMaxSize != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.CredentialSchemaSchemaMaxSize))
		i--
		dAtA[i] = 0x10
	}
	if m.CredentialSchemaTrustDeposit != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.CredentialSchemaTrustDeposit))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.CredentialSchemaTrustDeposit != 0 {
		n += 1 + sovParams(uint64(m.CredentialSchemaTrustDeposit))
	}
	if m.CredentialSchemaSchemaMaxSize != 0 {
		n += 1 + sovParams(uint64(m.CredentialSchemaSchemaMaxSize))
	}
	if m.CredentialSchemaIssuerGrantorValidationValidityPeriodMaxDays != 0 {
		n += 1 + sovParams(uint64(m.CredentialSchemaIssuerGrantorValidationValidityPeriodMaxDays))
	}
	if m.CredentialSchemaVerifierGrantorValidationValidityPeriodMaxDays != 0 {
		n += 1 + sovParams(uint64(m.CredentialSchemaVerifierGrantorValidationValidityPeriodMaxDays))
	}
	if m.CredentialSchemaIssuerValidationValidityPeriodMaxDays != 0 {
		n += 1 + sovParams(uint64(m.CredentialSchemaIssuerValidationValidityPeriodMaxDays))
	}
	if m.CredentialSchemaVerifierValidationValidityPeriodMaxDays != 0 {
		n += 1 + sovParams(uint64(m.CredentialSchemaVerifierValidationValidityPeriodMaxDays))
	}
	if m.CredentialSchemaHolderValidationValidityPeriodMaxDays != 0 {
		n += 1 + sovParams(uint64(m.CredentialSchemaHolderValidationValidityPeriodMaxDays))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CredentialSchemaTrustDeposit", wireType)
			}
			m.CredentialSchemaTrustDeposit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CredentialSchemaTrustDeposit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CredentialSchemaSchemaMaxSize", wireType)
			}
			m.CredentialSchemaSchemaMaxSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CredentialSchemaSchemaMaxSize |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CredentialSchemaIssuerGrantorValidationValidityPeriodMaxDays", wireType)
			}
			m.CredentialSchemaIssuerGrantorValidationValidityPeriodMaxDays = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CredentialSchemaIssuerGrantorValidationValidityPeriodMaxDays |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CredentialSchemaVerifierGrantorValidationValidityPeriodMaxDays", wireType)
			}
			m.CredentialSchemaVerifierGrantorValidationValidityPeriodMaxDays = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CredentialSchemaVerifierGrantorValidationValidityPeriodMaxDays |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CredentialSchemaIssuerValidationValidityPeriodMaxDays", wireType)
			}
			m.CredentialSchemaIssuerValidationValidityPeriodMaxDays = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CredentialSchemaIssuerValidationValidityPeriodMaxDays |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CredentialSchemaVerifierValidationValidityPeriodMaxDays", wireType)
			}
			m.CredentialSchemaVerifierValidationValidityPeriodMaxDays = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CredentialSchemaVerifierValidationValidityPeriodMaxDays |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CredentialSchemaHolderValidationValidityPeriodMaxDays", wireType)
			}
			m.CredentialSchemaHolderValidationValidityPeriodMaxDays = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CredentialSchemaHolderValidationValidityPeriodMaxDays |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
