// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: veranablockchain/credentialschema/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgUpdateParams is the Msg/UpdateParams request type.
type MsgUpdateParams struct {
	// authority is the address that controls the module (defaults to x/gov unless overwritten).
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// params defines the module parameters to update.
	//
	// NOTE: All parameters must be supplied.
	Params Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_6387a03fec1778ea, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// MsgUpdateParamsResponse defines the response structure for executing a
// MsgUpdateParams message.
type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6387a03fec1778ea, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

type MsgCreateCredentialSchema struct {
	Creator                                 string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	TrId                                    uint64 `protobuf:"varint,2,opt,name=tr_id,json=trId,proto3" json:"tr_id,omitempty"`
	JsonSchema                              string `protobuf:"bytes,3,opt,name=json_schema,json=jsonSchema,proto3" json:"json_schema,omitempty"`
	IssuerGrantorValidationValidityPeriod   uint32 `protobuf:"varint,4,opt,name=issuer_grantor_validation_validity_period,json=issuerGrantorValidationValidityPeriod,proto3" json:"issuer_grantor_validation_validity_period,omitempty"`
	VerifierGrantorValidationValidityPeriod uint32 `protobuf:"varint,5,opt,name=verifier_grantor_validation_validity_period,json=verifierGrantorValidationValidityPeriod,proto3" json:"verifier_grantor_validation_validity_period,omitempty"`
	IssuerValidationValidityPeriod          uint32 `protobuf:"varint,6,opt,name=issuer_validation_validity_period,json=issuerValidationValidityPeriod,proto3" json:"issuer_validation_validity_period,omitempty"`
	VerifierValidationValidityPeriod        uint32 `protobuf:"varint,7,opt,name=verifier_validation_validity_period,json=verifierValidationValidityPeriod,proto3" json:"verifier_validation_validity_period,omitempty"`
	HolderValidationValidityPeriod          uint32 `protobuf:"varint,8,opt,name=holder_validation_validity_period,json=holderValidationValidityPeriod,proto3" json:"holder_validation_validity_period,omitempty"`
	IssuerPermManagementMode                uint32 `protobuf:"varint,9,opt,name=issuer_perm_management_mode,json=issuerPermManagementMode,proto3" json:"issuer_perm_management_mode,omitempty"`
	VerifierPermManagementMode              uint32 `protobuf:"varint,10,opt,name=verifier_perm_management_mode,json=verifierPermManagementMode,proto3" json:"verifier_perm_management_mode,omitempty"`
}

func (m *MsgCreateCredentialSchema) Reset()         { *m = MsgCreateCredentialSchema{} }
func (m *MsgCreateCredentialSchema) String() string { return proto.CompactTextString(m) }
func (*MsgCreateCredentialSchema) ProtoMessage()    {}
func (*MsgCreateCredentialSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_6387a03fec1778ea, []int{2}
}
func (m *MsgCreateCredentialSchema) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateCredentialSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateCredentialSchema.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateCredentialSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateCredentialSchema.Merge(m, src)
}
func (m *MsgCreateCredentialSchema) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateCredentialSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateCredentialSchema.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateCredentialSchema proto.InternalMessageInfo

func (m *MsgCreateCredentialSchema) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateCredentialSchema) GetTrId() uint64 {
	if m != nil {
		return m.TrId
	}
	return 0
}

func (m *MsgCreateCredentialSchema) GetJsonSchema() string {
	if m != nil {
		return m.JsonSchema
	}
	return ""
}

func (m *MsgCreateCredentialSchema) GetIssuerGrantorValidationValidityPeriod() uint32 {
	if m != nil {
		return m.IssuerGrantorValidationValidityPeriod
	}
	return 0
}

func (m *MsgCreateCredentialSchema) GetVerifierGrantorValidationValidityPeriod() uint32 {
	if m != nil {
		return m.VerifierGrantorValidationValidityPeriod
	}
	return 0
}

func (m *MsgCreateCredentialSchema) GetIssuerValidationValidityPeriod() uint32 {
	if m != nil {
		return m.IssuerValidationValidityPeriod
	}
	return 0
}

func (m *MsgCreateCredentialSchema) GetVerifierValidationValidityPeriod() uint32 {
	if m != nil {
		return m.VerifierValidationValidityPeriod
	}
	return 0
}

func (m *MsgCreateCredentialSchema) GetHolderValidationValidityPeriod() uint32 {
	if m != nil {
		return m.HolderValidationValidityPeriod
	}
	return 0
}

func (m *MsgCreateCredentialSchema) GetIssuerPermManagementMode() uint32 {
	if m != nil {
		return m.IssuerPermManagementMode
	}
	return 0
}

func (m *MsgCreateCredentialSchema) GetVerifierPermManagementMode() uint32 {
	if m != nil {
		return m.VerifierPermManagementMode
	}
	return 0
}

type MsgCreateCredentialSchemaResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCreateCredentialSchemaResponse) Reset()         { *m = MsgCreateCredentialSchemaResponse{} }
func (m *MsgCreateCredentialSchemaResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateCredentialSchemaResponse) ProtoMessage()    {}
func (*MsgCreateCredentialSchemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6387a03fec1778ea, []int{3}
}
func (m *MsgCreateCredentialSchemaResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateCredentialSchemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateCredentialSchemaResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateCredentialSchemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateCredentialSchemaResponse.Merge(m, src)
}
func (m *MsgCreateCredentialSchemaResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateCredentialSchemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateCredentialSchemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateCredentialSchemaResponse proto.InternalMessageInfo

func (m *MsgCreateCredentialSchemaResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgUpdateCredentialSchema struct {
	Creator                                 string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id                                      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	IssuerGrantorValidationValidityPeriod   uint32 `protobuf:"varint,3,opt,name=issuer_grantor_validation_validity_period,json=issuerGrantorValidationValidityPeriod,proto3" json:"issuer_grantor_validation_validity_period,omitempty"`
	VerifierGrantorValidationValidityPeriod uint32 `protobuf:"varint,4,opt,name=verifier_grantor_validation_validity_period,json=verifierGrantorValidationValidityPeriod,proto3" json:"verifier_grantor_validation_validity_period,omitempty"`
	IssuerValidationValidityPeriod          uint32 `protobuf:"varint,5,opt,name=issuer_validation_validity_period,json=issuerValidationValidityPeriod,proto3" json:"issuer_validation_validity_period,omitempty"`
	VerifierValidationValidityPeriod        uint32 `protobuf:"varint,6,opt,name=verifier_validation_validity_period,json=verifierValidationValidityPeriod,proto3" json:"verifier_validation_validity_period,omitempty"`
	HolderValidationValidityPeriod          uint32 `protobuf:"varint,7,opt,name=holder_validation_validity_period,json=holderValidationValidityPeriod,proto3" json:"holder_validation_validity_period,omitempty"`
}

func (m *MsgUpdateCredentialSchema) Reset()         { *m = MsgUpdateCredentialSchema{} }
func (m *MsgUpdateCredentialSchema) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateCredentialSchema) ProtoMessage()    {}
func (*MsgUpdateCredentialSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_6387a03fec1778ea, []int{4}
}
func (m *MsgUpdateCredentialSchema) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateCredentialSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateCredentialSchema.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateCredentialSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateCredentialSchema.Merge(m, src)
}
func (m *MsgUpdateCredentialSchema) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateCredentialSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateCredentialSchema.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateCredentialSchema proto.InternalMessageInfo

func (m *MsgUpdateCredentialSchema) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateCredentialSchema) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgUpdateCredentialSchema) GetIssuerGrantorValidationValidityPeriod() uint32 {
	if m != nil {
		return m.IssuerGrantorValidationValidityPeriod
	}
	return 0
}

func (m *MsgUpdateCredentialSchema) GetVerifierGrantorValidationValidityPeriod() uint32 {
	if m != nil {
		return m.VerifierGrantorValidationValidityPeriod
	}
	return 0
}

func (m *MsgUpdateCredentialSchema) GetIssuerValidationValidityPeriod() uint32 {
	if m != nil {
		return m.IssuerValidationValidityPeriod
	}
	return 0
}

func (m *MsgUpdateCredentialSchema) GetVerifierValidationValidityPeriod() uint32 {
	if m != nil {
		return m.VerifierValidationValidityPeriod
	}
	return 0
}

func (m *MsgUpdateCredentialSchema) GetHolderValidationValidityPeriod() uint32 {
	if m != nil {
		return m.HolderValidationValidityPeriod
	}
	return 0
}

type MsgUpdateCredentialSchemaResponse struct {
}

func (m *MsgUpdateCredentialSchemaResponse) Reset()         { *m = MsgUpdateCredentialSchemaResponse{} }
func (m *MsgUpdateCredentialSchemaResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateCredentialSchemaResponse) ProtoMessage()    {}
func (*MsgUpdateCredentialSchemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6387a03fec1778ea, []int{5}
}
func (m *MsgUpdateCredentialSchemaResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateCredentialSchemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateCredentialSchemaResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateCredentialSchemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateCredentialSchemaResponse.Merge(m, src)
}
func (m *MsgUpdateCredentialSchemaResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateCredentialSchemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateCredentialSchemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateCredentialSchemaResponse proto.InternalMessageInfo

type MsgArchiveCredentialSchema struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Archive bool   `protobuf:"varint,3,opt,name=archive,proto3" json:"archive,omitempty"`
}

func (m *MsgArchiveCredentialSchema) Reset()         { *m = MsgArchiveCredentialSchema{} }
func (m *MsgArchiveCredentialSchema) String() string { return proto.CompactTextString(m) }
func (*MsgArchiveCredentialSchema) ProtoMessage()    {}
func (*MsgArchiveCredentialSchema) Descriptor() ([]byte, []int) {
	return fileDescriptor_6387a03fec1778ea, []int{6}
}
func (m *MsgArchiveCredentialSchema) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgArchiveCredentialSchema) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgArchiveCredentialSchema.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgArchiveCredentialSchema) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgArchiveCredentialSchema.Merge(m, src)
}
func (m *MsgArchiveCredentialSchema) XXX_Size() int {
	return m.Size()
}
func (m *MsgArchiveCredentialSchema) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgArchiveCredentialSchema.DiscardUnknown(m)
}

var xxx_messageInfo_MsgArchiveCredentialSchema proto.InternalMessageInfo

func (m *MsgArchiveCredentialSchema) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgArchiveCredentialSchema) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgArchiveCredentialSchema) GetArchive() bool {
	if m != nil {
		return m.Archive
	}
	return false
}

type MsgArchiveCredentialSchemaResponse struct {
}

func (m *MsgArchiveCredentialSchemaResponse) Reset()         { *m = MsgArchiveCredentialSchemaResponse{} }
func (m *MsgArchiveCredentialSchemaResponse) String() string { return proto.CompactTextString(m) }
func (*MsgArchiveCredentialSchemaResponse) ProtoMessage()    {}
func (*MsgArchiveCredentialSchemaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6387a03fec1778ea, []int{7}
}
func (m *MsgArchiveCredentialSchemaResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgArchiveCredentialSchemaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgArchiveCredentialSchemaResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgArchiveCredentialSchemaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgArchiveCredentialSchemaResponse.Merge(m, src)
}
func (m *MsgArchiveCredentialSchemaResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgArchiveCredentialSchemaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgArchiveCredentialSchemaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgArchiveCredentialSchemaResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "veranablockchain.credentialschema.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "veranablockchain.credentialschema.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgCreateCredentialSchema)(nil), "veranablockchain.credentialschema.MsgCreateCredentialSchema")
	proto.RegisterType((*MsgCreateCredentialSchemaResponse)(nil), "veranablockchain.credentialschema.MsgCreateCredentialSchemaResponse")
	proto.RegisterType((*MsgUpdateCredentialSchema)(nil), "veranablockchain.credentialschema.MsgUpdateCredentialSchema")
	proto.RegisterType((*MsgUpdateCredentialSchemaResponse)(nil), "veranablockchain.credentialschema.MsgUpdateCredentialSchemaResponse")
	proto.RegisterType((*MsgArchiveCredentialSchema)(nil), "veranablockchain.credentialschema.MsgArchiveCredentialSchema")
	proto.RegisterType((*MsgArchiveCredentialSchemaResponse)(nil), "veranablockchain.credentialschema.MsgArchiveCredentialSchemaResponse")
}

func init() {
	proto.RegisterFile("veranablockchain/credentialschema/tx.proto", fileDescriptor_6387a03fec1778ea)
}

var fileDescriptor_6387a03fec1778ea = []byte{
	// 776 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x96, 0x4d, 0x4f, 0xdb, 0x48,
	0x1c, 0xc6, 0xe3, 0x90, 0x17, 0x32, 0xb0, 0xbb, 0x5a, 0x2f, 0x5a, 0x8c, 0xab, 0x86, 0x10, 0x5a,
	0x15, 0x52, 0x91, 0xa8, 0x41, 0xea, 0x01, 0xc1, 0x21, 0xd0, 0x17, 0x21, 0x35, 0x12, 0x32, 0x2a,
	0xaa, 0xda, 0x4a, 0xd6, 0xc4, 0x9e, 0x3a, 0xd3, 0xc6, 0x9e, 0x68, 0x66, 0x88, 0xe0, 0x52, 0x55,
	0x3d, 0x55, 0x9c, 0xfa, 0x01, 0x2a, 0xf5, 0xda, 0x23, 0xaa, 0xfa, 0x21, 0x38, 0xa2, 0x9e, 0x7a,
	0x6a, 0x2b, 0x38, 0x70, 0xe9, 0x87, 0xa8, 0x32, 0x63, 0x1b, 0x61, 0x70, 0x12, 0x0a, 0x5c, 0x12,
	0x7b, 0xe6, 0xf9, 0xff, 0xe6, 0xf9, 0x5b, 0x8f, 0x3d, 0x03, 0x4a, 0x1d, 0x44, 0xa1, 0x07, 0x1b,
	0x2d, 0x62, 0xbd, 0xb2, 0x9a, 0x10, 0x7b, 0x15, 0x8b, 0x22, 0x1b, 0x79, 0x1c, 0xc3, 0x16, 0xb3,
	0x9a, 0xc8, 0x85, 0x15, 0xbe, 0x55, 0x6e, 0x53, 0xc2, 0x89, 0x3a, 0x15, 0xd5, 0x96, 0xa3, 0x5a,
	0xfd, 0x5f, 0xe8, 0x62, 0x8f, 0x54, 0xc4, 0xaf, 0xac, 0xd2, 0xc7, 0x2d, 0xc2, 0x5c, 0xc2, 0x2a,
	0x2e, 0x73, 0x2a, 0x9d, 0x3b, 0xdd, 0x3f, 0x7f, 0x62, 0x42, 0x4e, 0x98, 0xe2, 0xae, 0x22, 0x6f,
	0xfc, 0xa9, 0x31, 0x87, 0x38, 0x44, 0x8e, 0x77, 0xaf, 0xfc, 0xd1, 0x72, 0x7f, 0xaf, 0x6d, 0x48,
	0xa1, 0x1b, 0x50, 0xe6, 0x06, 0xe8, 0x6d, 0xbb, 0x8d, 0x7c, 0x79, 0xf1, 0x87, 0x02, 0xfe, 0xa9,
	0x33, 0xe7, 0x71, 0xdb, 0x86, 0x1c, 0xad, 0x09, 0x90, 0x7a, 0x17, 0xe4, 0xe0, 0x26, 0x6f, 0x12,
	0x8a, 0xf9, 0xb6, 0xa6, 0x14, 0x94, 0x99, 0xdc, 0xb2, 0xf6, 0xf5, 0xcb, 0xdc, 0x98, 0xef, 0xb6,
	0x66, 0xdb, 0x14, 0x31, 0xb6, 0xce, 0x29, 0xf6, 0x1c, 0xe3, 0x58, 0xaa, 0x3e, 0x02, 0x19, 0x69,
	0x45, 0x4b, 0x16, 0x94, 0x99, 0x91, 0xea, 0x6c, 0xb9, 0xef, 0xb3, 0x2b, 0xcb, 0x25, 0x97, 0x73,
	0x7b, 0xdf, 0x27, 0x13, 0x9f, 0x8e, 0x76, 0x4b, 0x8a, 0xe1, 0x33, 0x16, 0x1e, 0xbc, 0x3d, 0xda,
	0x2d, 0x1d, 0xd3, 0x77, 0x8e, 0x76, 0x4b, 0xf3, 0xa7, 0x7a, 0xdb, 0x3a, 0xdd, 0x5d, 0xa4, 0x9b,
	0xe2, 0x04, 0x18, 0x8f, 0x0c, 0x19, 0x88, 0xb5, 0x89, 0xc7, 0x50, 0xf1, 0x73, 0x1a, 0x4c, 0xd4,
	0x99, 0xb3, 0x42, 0x11, 0xe4, 0x68, 0x25, 0x04, 0xad, 0x0b, 0x90, 0x5a, 0x05, 0x59, 0xab, 0x3b,
	0x43, 0x68, 0xdf, 0x87, 0x10, 0x08, 0xd5, 0xff, 0x40, 0x9a, 0x53, 0x13, 0xdb, 0xe2, 0x09, 0xa4,
	0x8c, 0x14, 0xa7, 0xab, 0xb6, 0x3a, 0x09, 0x46, 0x5e, 0x32, 0xe2, 0x99, 0xd2, 0xa0, 0x36, 0xd4,
	0x85, 0x19, 0xa0, 0x3b, 0xe4, 0xaf, 0xf4, 0x04, 0xcc, 0x62, 0xc6, 0x36, 0x11, 0x35, 0x1d, 0x0a,
	0x3d, 0x4e, 0xa8, 0xd9, 0x81, 0x2d, 0x6c, 0x43, 0x8e, 0x89, 0x27, 0x2f, 0x31, 0xdf, 0x36, 0xdb,
	0x88, 0x62, 0x62, 0x6b, 0xa9, 0x82, 0x32, 0xf3, 0x97, 0x71, 0x53, 0x16, 0x3c, 0x94, 0xfa, 0x8d,
	0x50, 0xbe, 0xe1, 0xab, 0xd7, 0x84, 0x58, 0x7d, 0x0e, 0x6e, 0x77, 0x10, 0xc5, 0x2f, 0xf0, 0x60,
	0xec, 0xb4, 0x60, 0xdf, 0x0a, 0x4a, 0xfa, 0xd1, 0x57, 0xc1, 0x94, 0xef, 0xbb, 0x07, 0x33, 0x23,
	0x98, 0x79, 0x29, 0x8c, 0x45, 0xd5, 0xc1, 0x74, 0x68, 0xb4, 0x07, 0x2c, 0x2b, 0x60, 0x85, 0x40,
	0xda, 0xcb, 0x59, 0x93, 0xb4, 0xec, 0xde, 0xb0, 0x61, 0xe9, 0x4c, 0x0a, 0x63, 0x51, 0x4b, 0xe0,
	0x9a, 0xdf, 0x64, 0x1b, 0x51, 0xd7, 0x74, 0xa1, 0x07, 0x1d, 0xe4, 0x22, 0x8f, 0x9b, 0x2e, 0xb1,
	0x91, 0x96, 0x13, 0x10, 0x4d, 0x4a, 0xd6, 0x10, 0x75, 0xeb, 0xa1, 0xa0, 0x4e, 0x6c, 0xa4, 0xd6,
	0xc0, 0xf5, 0xb0, 0xb1, 0x33, 0x01, 0x40, 0x00, 0xf4, 0x40, 0x74, 0x1a, 0xb1, 0x30, 0xda, 0x7d,
	0x13, 0x82, 0x88, 0x15, 0xe7, 0xc1, 0x54, 0x6c, 0x66, 0x83, 0x64, 0xab, 0x7f, 0x83, 0x24, 0xb6,
	0x45, 0x6c, 0x53, 0x46, 0x12, 0xdb, 0xc5, 0x9d, 0x94, 0x48, 0xba, 0x7c, 0x0b, 0x2e, 0x25, 0xe9,
	0x72, 0x85, 0x64, 0xb0, 0xc2, 0xf9, 0x32, 0x3c, 0x74, 0x85, 0x19, 0x4e, 0x5d, 0x41, 0x86, 0xd3,
	0x97, 0x99, 0xe1, 0xcc, 0x65, 0x66, 0x38, 0x3b, 0x48, 0x86, 0x23, 0x09, 0x9a, 0x16, 0x09, 0x3a,
	0x3b, 0x0b, 0xe1, 0xb7, 0xf1, 0x9d, 0x02, 0xf4, 0x3a, 0x73, 0x6a, 0xd4, 0x6a, 0xe2, 0xce, 0xd5,
	0x44, 0x46, 0x03, 0x59, 0x28, 0xf1, 0x22, 0x10, 0xc3, 0x46, 0x70, 0x1b, 0xf1, 0x7b, 0x03, 0x14,
	0xe3, 0x9d, 0x04, 0x86, 0xab, 0xbf, 0x52, 0x60, 0xa8, 0xce, 0x1c, 0xf5, 0x35, 0x18, 0x3d, 0xb1,
	0x9b, 0x55, 0x07, 0xd8, 0x85, 0x22, 0x1b, 0x84, 0xbe, 0x70, 0xfe, 0x9a, 0xf0, 0xd5, 0xfb, 0xa0,
	0x80, 0xff, 0x63, 0x76, 0x94, 0xc5, 0xc1, 0xb0, 0x67, 0x57, 0xeb, 0xf7, 0x2e, 0x52, 0x7d, 0xc2,
	0x5e, 0xcc, 0x67, 0x60, 0xf1, 0x3c, 0x5d, 0xff, 0xa9, 0xbd, 0xde, 0xb1, 0x53, 0x3f, 0x2a, 0x60,
	0x3c, 0x2e, 0x73, 0x4b, 0x83, 0xad, 0x10, 0x53, 0xae, 0xdf, 0xbf, 0x50, 0x79, 0xe0, 0x50, 0x4f,
	0xbf, 0xe9, 0x1e, 0x53, 0x96, 0x9f, 0xed, 0x1d, 0xe4, 0x95, 0xfd, 0x83, 0xbc, 0xf2, 0xf3, 0x20,
	0xaf, 0xbc, 0x3f, 0xcc, 0x27, 0xf6, 0x0f, 0xf3, 0x89, 0x6f, 0x87, 0xf9, 0xc4, 0xd3, 0x9a, 0x83,
	0x79, 0x73, 0xb3, 0x51, 0xb6, 0x88, 0x5b, 0x91, 0x2b, 0xce, 0xb5, 0x60, 0x83, 0x05, 0xd7, 0xbd,
	0x4f, 0x2f, 0xe2, 0x6c, 0xd6, 0xc8, 0x88, 0xc3, 0xd9, 0xfc, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x83, 0x75, 0x30, 0x3b, 0xa9, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	// CreateCredentialSchema defines a method for creating a new credential schema.
	CreateCredentialSchema(ctx context.Context, in *MsgCreateCredentialSchema, opts ...grpc.CallOption) (*MsgCreateCredentialSchemaResponse, error)
	// UpdateCredentialSchema defines a method for updating a credential schema.
	UpdateCredentialSchema(ctx context.Context, in *MsgUpdateCredentialSchema, opts ...grpc.CallOption) (*MsgUpdateCredentialSchemaResponse, error)
	// ArchiveCredentialSchema defines a method for archiving a credential schema.
	ArchiveCredentialSchema(ctx context.Context, in *MsgArchiveCredentialSchema, opts ...grpc.CallOption) (*MsgArchiveCredentialSchemaResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/veranablockchain.credentialschema.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateCredentialSchema(ctx context.Context, in *MsgCreateCredentialSchema, opts ...grpc.CallOption) (*MsgCreateCredentialSchemaResponse, error) {
	out := new(MsgCreateCredentialSchemaResponse)
	err := c.cc.Invoke(ctx, "/veranablockchain.credentialschema.Msg/CreateCredentialSchema", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateCredentialSchema(ctx context.Context, in *MsgUpdateCredentialSchema, opts ...grpc.CallOption) (*MsgUpdateCredentialSchemaResponse, error) {
	out := new(MsgUpdateCredentialSchemaResponse)
	err := c.cc.Invoke(ctx, "/veranablockchain.credentialschema.Msg/UpdateCredentialSchema", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) ArchiveCredentialSchema(ctx context.Context, in *MsgArchiveCredentialSchema, opts ...grpc.CallOption) (*MsgArchiveCredentialSchemaResponse, error) {
	out := new(MsgArchiveCredentialSchemaResponse)
	err := c.cc.Invoke(ctx, "/veranablockchain.credentialschema.Msg/ArchiveCredentialSchema", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// UpdateParams defines a (governance) operation for updating the module
	// parameters. The authority defaults to the x/gov module account.
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	// CreateCredentialSchema defines a method for creating a new credential schema.
	CreateCredentialSchema(context.Context, *MsgCreateCredentialSchema) (*MsgCreateCredentialSchemaResponse, error)
	// UpdateCredentialSchema defines a method for updating a credential schema.
	UpdateCredentialSchema(context.Context, *MsgUpdateCredentialSchema) (*MsgUpdateCredentialSchemaResponse, error)
	// ArchiveCredentialSchema defines a method for archiving a credential schema.
	ArchiveCredentialSchema(context.Context, *MsgArchiveCredentialSchema) (*MsgArchiveCredentialSchemaResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) CreateCredentialSchema(ctx context.Context, req *MsgCreateCredentialSchema) (*MsgCreateCredentialSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCredentialSchema not implemented")
}
func (*UnimplementedMsgServer) UpdateCredentialSchema(ctx context.Context, req *MsgUpdateCredentialSchema) (*MsgUpdateCredentialSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCredentialSchema not implemented")
}
func (*UnimplementedMsgServer) ArchiveCredentialSchema(ctx context.Context, req *MsgArchiveCredentialSchema) (*MsgArchiveCredentialSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ArchiveCredentialSchema not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/veranablockchain.credentialschema.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateCredentialSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateCredentialSchema)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateCredentialSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/veranablockchain.credentialschema.Msg/CreateCredentialSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateCredentialSchema(ctx, req.(*MsgCreateCredentialSchema))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateCredentialSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateCredentialSchema)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateCredentialSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/veranablockchain.credentialschema.Msg/UpdateCredentialSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateCredentialSchema(ctx, req.(*MsgUpdateCredentialSchema))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_ArchiveCredentialSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgArchiveCredentialSchema)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ArchiveCredentialSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/veranablockchain.credentialschema.Msg/ArchiveCredentialSchema",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ArchiveCredentialSchema(ctx, req.(*MsgArchiveCredentialSchema))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "veranablockchain.credentialschema.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "CreateCredentialSchema",
			Handler:    _Msg_CreateCredentialSchema_Handler,
		},
		{
			MethodName: "UpdateCredentialSchema",
			Handler:    _Msg_UpdateCredentialSchema_Handler,
		},
		{
			MethodName: "ArchiveCredentialSchema",
			Handler:    _Msg_ArchiveCredentialSchema_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "veranablockchain/credentialschema/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCreateCredentialSchema) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateCredentialSchema) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateCredentialSchema) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.VerifierPermManagementMode != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.VerifierPermManagementMode))
		i--
		dAtA[i] = 0x50
	}
	if m.IssuerPermManagementMode != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.IssuerPermManagementMode))
		i--
		dAtA[i] = 0x48
	}
	if m.HolderValidationValidityPeriod != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.HolderValidationValidityPeriod))
		i--
		dAtA[i] = 0x40
	}
	if m.VerifierValidationValidityPeriod != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.VerifierValidationValidityPeriod))
		i--
		dAtA[i] = 0x38
	}
	if m.IssuerValidationValidityPeriod != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.IssuerValidationValidityPeriod))
		i--
		dAtA[i] = 0x30
	}
	if m.VerifierGrantorValidationValidityPeriod != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.VerifierGrantorValidationValidityPeriod))
		i--
		dAtA[i] = 0x28
	}
	if m.IssuerGrantorValidationValidityPeriod != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.IssuerGrantorValidationValidityPeriod))
		i--
		dAtA[i] = 0x20
	}
	if len(m.JsonSchema) > 0 {
		i -= len(m.JsonSchema)
		copy(dAtA[i:], m.JsonSchema)
		i = encodeVarintTx(dAtA, i, uint64(len(m.JsonSchema)))
		i--
		dAtA[i] = 0x1a
	}
	if m.TrId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.TrId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateCredentialSchemaResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateCredentialSchemaResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateCredentialSchemaResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateCredentialSchema) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateCredentialSchema) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateCredentialSchema) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.HolderValidationValidityPeriod != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.HolderValidationValidityPeriod))
		i--
		dAtA[i] = 0x38
	}
	if m.VerifierValidationValidityPeriod != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.VerifierValidationValidityPeriod))
		i--
		dAtA[i] = 0x30
	}
	if m.IssuerValidationValidityPeriod != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.IssuerValidationValidityPeriod))
		i--
		dAtA[i] = 0x28
	}
	if m.VerifierGrantorValidationValidityPeriod != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.VerifierGrantorValidationValidityPeriod))
		i--
		dAtA[i] = 0x20
	}
	if m.IssuerGrantorValidationValidityPeriod != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.IssuerGrantorValidationValidityPeriod))
		i--
		dAtA[i] = 0x18
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateCredentialSchemaResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateCredentialSchemaResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateCredentialSchemaResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgArchiveCredentialSchema) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgArchiveCredentialSchema) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgArchiveCredentialSchema) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Archive {
		i--
		if m.Archive {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgArchiveCredentialSchemaResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgArchiveCredentialSchemaResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgArchiveCredentialSchemaResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCreateCredentialSchema) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.TrId != 0 {
		n += 1 + sovTx(uint64(m.TrId))
	}
	l = len(m.JsonSchema)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.IssuerGrantorValidationValidityPeriod != 0 {
		n += 1 + sovTx(uint64(m.IssuerGrantorValidationValidityPeriod))
	}
	if m.VerifierGrantorValidationValidityPeriod != 0 {
		n += 1 + sovTx(uint64(m.VerifierGrantorValidationValidityPeriod))
	}
	if m.IssuerValidationValidityPeriod != 0 {
		n += 1 + sovTx(uint64(m.IssuerValidationValidityPeriod))
	}
	if m.VerifierValidationValidityPeriod != 0 {
		n += 1 + sovTx(uint64(m.VerifierValidationValidityPeriod))
	}
	if m.HolderValidationValidityPeriod != 0 {
		n += 1 + sovTx(uint64(m.HolderValidationValidityPeriod))
	}
	if m.IssuerPermManagementMode != 0 {
		n += 1 + sovTx(uint64(m.IssuerPermManagementMode))
	}
	if m.VerifierPermManagementMode != 0 {
		n += 1 + sovTx(uint64(m.VerifierPermManagementMode))
	}
	return n
}

func (m *MsgCreateCredentialSchemaResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgUpdateCredentialSchema) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	if m.IssuerGrantorValidationValidityPeriod != 0 {
		n += 1 + sovTx(uint64(m.IssuerGrantorValidationValidityPeriod))
	}
	if m.VerifierGrantorValidationValidityPeriod != 0 {
		n += 1 + sovTx(uint64(m.VerifierGrantorValidationValidityPeriod))
	}
	if m.IssuerValidationValidityPeriod != 0 {
		n += 1 + sovTx(uint64(m.IssuerValidationValidityPeriod))
	}
	if m.VerifierValidationValidityPeriod != 0 {
		n += 1 + sovTx(uint64(m.VerifierValidationValidityPeriod))
	}
	if m.HolderValidationValidityPeriod != 0 {
		n += 1 + sovTx(uint64(m.HolderValidationValidityPeriod))
	}
	return n
}

func (m *MsgUpdateCredentialSchemaResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgArchiveCredentialSchema) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	if m.Archive {
		n += 2
	}
	return n
}

func (m *MsgArchiveCredentialSchemaResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateCredentialSchema) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateCredentialSchema: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateCredentialSchema: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrId", wireType)
			}
			m.TrId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TrId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JsonSchema", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JsonSchema = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuerGrantorValidationValidityPeriod", wireType)
			}
			m.IssuerGrantorValidationValidityPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IssuerGrantorValidationValidityPeriod |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifierGrantorValidationValidityPeriod", wireType)
			}
			m.VerifierGrantorValidationValidityPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VerifierGrantorValidationValidityPeriod |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuerValidationValidityPeriod", wireType)
			}
			m.IssuerValidationValidityPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IssuerValidationValidityPeriod |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifierValidationValidityPeriod", wireType)
			}
			m.VerifierValidationValidityPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VerifierValidationValidityPeriod |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HolderValidationValidityPeriod", wireType)
			}
			m.HolderValidationValidityPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HolderValidationValidityPeriod |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuerPermManagementMode", wireType)
			}
			m.IssuerPermManagementMode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IssuerPermManagementMode |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifierPermManagementMode", wireType)
			}
			m.VerifierPermManagementMode = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VerifierPermManagementMode |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateCredentialSchemaResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateCredentialSchemaResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateCredentialSchemaResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateCredentialSchema) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateCredentialSchema: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateCredentialSchema: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuerGrantorValidationValidityPeriod", wireType)
			}
			m.IssuerGrantorValidationValidityPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IssuerGrantorValidationValidityPeriod |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifierGrantorValidationValidityPeriod", wireType)
			}
			m.VerifierGrantorValidationValidityPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VerifierGrantorValidationValidityPeriod |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuerValidationValidityPeriod", wireType)
			}
			m.IssuerValidationValidityPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IssuerValidationValidityPeriod |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifierValidationValidityPeriod", wireType)
			}
			m.VerifierValidationValidityPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VerifierValidationValidityPeriod |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HolderValidationValidityPeriod", wireType)
			}
			m.HolderValidationValidityPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HolderValidationValidityPeriod |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateCredentialSchemaResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateCredentialSchemaResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateCredentialSchemaResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgArchiveCredentialSchema) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgArchiveCredentialSchema: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgArchiveCredentialSchema: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Archive", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Archive = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgArchiveCredentialSchemaResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgArchiveCredentialSchemaResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgArchiveCredentialSchemaResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
